# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Portail G9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Portail G9
  pod 'IQKeyboardManagerSwift'

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Crashlytics'

  pod 'SDWebImage'
  pod 'ReachabilitySwift'
  
  pod 'NVActivityIndicatorView'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  
  pod 'SideMenu'

  pod 'CollapsibleTableSectionViewController'
  pod 'AAInfographics'
  pod 'ABGaugeViewKit'
  pod 'RSSelectionMenu'
  
  
  
  target 'Portail G9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Portail G9UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
