# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Portail G9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Portail G9



  target 'Portail G9Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Portail G9UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
